deploy:
  type: git
  repo: https://github.com/secretlittleboy/secretlittleboy.github.io
  branch: gh-pages

theme: butterfly
title: Yihao Long 's Blog
subtitle: don't update often,hahağŸ¥³
description: My blog here, welcome to visit!<br/> However, I prefer to use Feishu to record my learning notes.<br/> I will share the Feishu link here. 
keywords: Yihao Long, Yihao, Long, Yihao Long's Blog
author: Yihao Long
language: zh-CN

search:
  path: search.xml
  field: all # post:æ–‡ç« èŒƒå›´ã€page:é¡µé¢èŒƒå›´ã€all:è¦†ç›–æ‰€æœ‰
  content: true # å†…å®¹æ˜¯å¦åŒ…å«æ¯ä¸€ç¯‡æ–‡ç« çš„å…¨éƒ¨å†…å®¹
  template:  # ./search.xml æŒ‡å®šå®šåˆ¶çš„XMLæ¨¡æ¿